### ISSUE TITLE
JitsiLocalScreenRecorder can use it for mobile app?

### ISSUE THREAD

**Issue by beheobong** [TALRACE/LocalScreenRecorder#1]

**Comment by MichaelStark** [comment]
No. Only desktop web browser and electron application. Mobile OSs have limitations and certain inconveniences with screen recording. If this is important to you, then the only way is Jibri.

**Comment by beheobong** [comment]
thank you so much. And Are you try Jibri for mobile app? It working?

**Comment by MichaelStark** [comment]
Jibri works on the server side. The button to start recording will simply be available in the mobile application.

**Comment by beheobong** [comment]
> Jibri works on the server side. The button to start recording will simply be available in the mobile application.

it mean recording by server and mobile app download it ?

**Comment by MichaelStark** [comment]
I haven't tried it but I don't see any problem with mobile apps. There you need to connect a dropbox account and there should be no problems with downloading. It's another matter if you want without dropbox account and the files are saved on the jibri server. In this case, you have to implement the api for download the file or somehow transfer the file to another server where the api for download has already been implemented

**Comment by beheobong** [comment]
> I haven't tried it but I don't see any problem with mobile apps. There you need to connect a dropbox account and there should be no problems with downloading. It's another matter if you want without dropbox account and the files are saved on the jibri server. In this case, you have to implement the api for download the file or somehow transfer the file to another server where the api for download has already been implemented

ok, i will try it. thank you so much
