### ISSUE TITLE
JitsiLocalScreenRecorder can it handle the new participants' audio stream?

### ISSUE THREAD

**Issue by Nayeem0072** [TALRACE/LocalScreenRecorder#2]
First of all, this JitsiLocalScreenRecorder has been very helpful as it provides some important ideas that are integral to the part of a local conference recorder.

Pardon me as I don't have the chance to test it yet, but can this code support the audio streams of a new participant that is joined after the recording has been started? I checked the code and didn't see that use case handled, but I could be very wrong (and I will be delete this thread if that happens).

If this code doesn't handle the case of new participants joining, can you provide some suggestion whether I can add some audio stream of the new participant when a recording session is ongoing (and without stopping the recording session)? 

Thanks.

**Comment by MichaelStark** [comment]
Yes.
Initially, when designing, we discussed this case and others, for example, when there are no audio streams at all and when audio stream suddenly appeared. So there is a code that generates an empty audio stream for these cases. For your case, you just need to look at line 101: `APP.conference._room.on(JitsiMeetJS.events.conference.TRACK_ADDED, trackAddedHandler);`

**Comment by Nayeem0072** [comment]
Yes, I can see it now, thanks for your reply! 
I will test it very soon, this looks very fitting to my requirements for local jitsi recordings.

Thanks again for all the hard work on it.
